### ISSUE TITLE
CPU usage 100% on at least one core when bridge cannot be found

### ISSUE THREAD

**Issue by Ch3wi3** [Fuchs/hoppla-sa#2] opened 2017-02-01 12:25 UTC
On my Kubuntu 16.10 Laptop the plasmoid does not find the bridge (see issue : https://github.com/Fuchs/hoppla-sa/issues/1) 

Immediately after not finding the bridge, the CPU usage on at least one of my cpu cores strikes 100% and remains there until I remove the widget from my desktop

**Comment by Fuchs** [comment] 2017-02-01 13:36
Hi, unfortunately I am not able to reproduce that here, neither in the systray nor on the desktop. Could you do the following: 

go to where the plasmoid is installed  (probably ~/.local/share/plasma/plasmoids/ch.fuchsnet.plasma.hoppla-sa/contents/) and open the files 

code/hue.js 

and 

ui/main.qml 

and change the debug value from "false" to "true" with a text editor, then save it. 
Then please kill plasmashell in a terminal and restart it in said terminal. 
See if there is any helpful debug output that could explain the load. 

You can also do that to debug the lights not working. 

If that doesn't work, it would be super handy if I could get a json dump of your hue bridge. 
To get that, open 

https://1.2.3.4/api/AuthToken/

in a web browser, replacing 1.2.3.4 with your hue bridge IP and AuthToken with the auth token (you can copy that from the configuation dialogue) 

Feel free to edit any personal information  (Light / Group names) out of it, definitely do edit all Auth Tokens out of it. 

Thanks in advance, kind regards

**Comment by Ch3wi3** [comment] 2017-02-01 14:17
Ok I think the problem with my light command was, that I forgot to add the State "on" to my "action". Again -> when creating an action, why should it doesn't include an "state=on" by default? In that case I would not have experienced this problem. 

Regarding the 100% CPU issue: 

here is the only output I could relate to hoppla: 

`file:///home/chewie/.local/share/plasma/plasmoids/ch.fuchsnet.plasma.hoppla-sa/contents /ui/configBridge.qml:53:9: QML GroupBox: Binding loop detected for  property "implicitWidth"`

**Comment by Fuchs** [comment] 2017-02-01 14:28
Okay, thanks. 

For 
> Again -> when creating an action, why should it doesn't include an "state=on" by default? 

It doesn't because there plenty of use cases where this is not wanted. E.g. in an action "dim all active lights" you don't want to include the on state at all, whilst for "turn off all lights" you want it to be set off. Unfortunately all 3 cases (on=true, on=false, no on at all) are valid, thus  "don't set one, as with all other options" is the most sane default.

I'll close this for now, if you get the 100% again, please tell me

- What version of KDE
- What version of Qt 
- What plasma theme
- What icon theme

you are using. Thanks :)

**Closed by Fuchs** 2017-02-01 14:28 UTC
